### ISSUE TITLE
Find Customer by Name

### ISSUE THREAD

**Issue by JulianGan** [CSCI-GA-2820-FA24-001/customers#29]
**As a** customer rep
**I need** to list and filter by name
**So that** I can find people easily

**Details & Assumptions:**
- list and query by attribute should already be implemented

**Acceptance Criteria:**
```
Given a string argument 'name'
When I query on the name attribute for 'name'
Then I should receive a list of entries with the matching name
```

**Comment by molliey** [comment]
I think the story title can be more specific such as Find Customers by Name.
